image:
  file: .gitpod.Dockerfile


# exposed ports
ports:
- port: 3000 # preview on browser
  onOpen: open-browser

tasks:
  - init: |
      echo "Building from source..."
      ./bin/build
    command: |
      ls target/uberjar
      java -jar target/uberjar/metabase.jar
  - command: gp await-port 3000 && gp preview "$(gp url 3000)"

# You can download and run metabase from
# wget https://downloads.metabase.com/v0.39.4/metabase.jar -O metabase.jar
# java -jar metabase.jar
